### ISSUE TITLE
UserAccountDetal component is returning IPFS link

### ISSUE THREAD

**Issue by personnamedmike** [airswap/airswap-voter-rewards#108]
If a user has an avatar on their ENS, we show the URL in the disconnect popover instead of using it as the src for an image element

![image](https://github.com/airswap/airswap-voter-rewards/assets/90465420/651b8ca8-3594-43c1-859a-4ed057e4c618)

**Comment by personnamedmike** [comment]
PR linked https://github.com/airswap/airswap-voter-rewards/pull/118

**Comment by gpxl-dev** [comment]
FYI you can use `closes #118` in the PR body and it'll auto-close the issue when they're merged.
