### ISSUE TITLE
Fix PieBar proportions on Firefox

### ISSUE THREAD

**Issue by personnamedmike** [airswap/airswap-voter-rewards#115]
Looks fine on Brave, but on Firefox it's off. Should span the entire width 

<img width="343" alt="Screenshot 2023-10-06 at 10 21 38 AM" src="https://github.com/airswap/airswap-voter-rewards/assets/90465420/96be773e-0539-408f-ab4b-0ef471c18c5d">

**Comment by gpxl-dev** [comment]
Can't reproduce this.

**Comment by personnamedmike** [comment]
I'll work on this one

**Comment by personnamedmike** [comment]
Fixed in PR https://github.com/airswap/airswap-voter-rewards/pull/126
