### ISSUE TITLE
Claim Float component

### ISSUE THREAD

**Issue by personnamedmike** [airswap/airswap-voter-rewards#5]
![Screenshot 2023-07-25 at 11 04 20 AM](https://github.com/airswap/airswap-voter-rewards/assets/90465420/ecf35702-027c-430e-b7ae-07a05131a9ba)

mobile claim float:
![Screenshot 2023-07-25 at 11 08 14 AM](https://github.com/airswap/airswap-voter-rewards/assets/90465420/7818ae8f-6312-4ec3-9bb2-a7f720f969a4)

**Comment by gpxl-dev** [comment]
#25
